version: "3"

services:
  calculadoradejuros:
    image: calculadoradejuros:1.2
    build:
      context: .
    ports:
      - "5000:80"
    networks:
      - taxas-network
    depends_on:
      - "taxas"

  taxas:
    image: taxas:1.0
    ports:
      - "5001:80"
    networks:
      - taxas-network

networks: 
    taxas-network:
        driver: bridge