version: "3.7"

services:
  calculadoradejuros:
    image: joaofelipegoncalves/calculadoradejuros:1.0
    build:
      context: .
    ports:
      - "5000:80"
    networks:
      - taxas-network
    depends_on:
      - "taxas"

  taxas:
    image: joaofelipegoncalves/taxas:1.0
    ports:
      - "5001:80"
    networks:
      - taxas-network
    depends_on:
      - "sqldatabase"

  sqldatabase:
    container_name: sqldatabase
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "SQLTaxas123"
      ACCEPT_EULA: "Y"
    networks:
      - taxas-network

networks: 
    taxas-network:
        driver: bridge